---
- name: Install net-tools for old ifconfig
  tags: local,packages
  yum: name=net-tools state=installed

- name: Install bind-utils for e.g. dig
  tags: local,packages
  yum: name=bind-utils state=installed

- name: Install mlocate
  tags: local,packages
  yum: name=mlocate state=installed

- name: Install zsh
  tags: local,packages
  yum: name=zsh state=installed

- name: package smbios fixes in base repo
  tags: yum,fixes
  yum_repository:
    name: base
    file: CentOS-Base
    description: "CentOS-$releasever - Base"
    mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra"
    exclude: "*smbios*"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
    gpgcheck: true

- name: package smbios fixes in updates repo
  tags: yum,fixes
  yum_repository:
    name: updates
    file: CentOS-Base
    description: "CentOS-$releasever - Updates"
    mirrorlist: "http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra"
    exclude: "*smbios*"
    gpgkey: "file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7"
    gpgcheck: true
#- name: Add local Mellanox-repo
#  tags: ib
#  yum_repository:
#    name: local-mellanox 
#    description: Mellanox IB-stack repo
#    #baseurl: file:///home/Mellanox-repo/RPMS
#    baseurl: "http://{{ kickstart_server_ip }}/Mellanox-repo/{{ ansible_distribution_major_version }}"
#    gpgcheck: no
#  when: rdma_type is defined and rdma_type == "mlnx_ofed"

